version: "3.7"
services:
  api:
    image: gymbroapi
    container_name: gymbro-api
    ports:
      - 8080:8080
    environment:
      - DATABASE_CONNECTION=postgresql://root:password@gymbro_postgres:5432/gymbro_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json

  postgres:
    image: postgres:15.1-alpine
    container_name: gymbro_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gymbro_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "gymbro_db"]
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
